language: php
sudo: false
dist: trusty

branches:
  only:
    - master

php:
  - 7.2

services:
  - mysql

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - vendor
    - ./bin/.phpunit

env:
  global:
    - APP_ENV: test
    - DATABASE_URL: mysql://root:@127.0.0.1:3306/test
    - JWT_SECRET_KEY: config/jwt/test/private.pem
    - JWT_PUBLIC_KEY: config/jwt/test/public.pem
    - JWT_PASSPHRASE: s3cr3tf0rt3st
    - JWT_TOKENTTL: 3600

before_install:
  - composer self-update
  - openssl genrsa -passout pass:$JWT_PASSPHRASE -out $JWT_SECRET_KEY -aes256 4096
  - openssl rsa -pubout -in $JWT_SECRET_KEY -passin pass:$JWT_PASSPHRASE -out $JWT_PUBLIC_KEY

install:
  - composer install
  - php bin/phpunit install

before_script:
  - php bin/console doctrine:database:drop --if-exists --force
  - php bin/console doctrine:database:create --if-not-exists
  - php bin/console doctrine:schema:update --force
  - php bin/console doctrine:fixtures:load --no-interaction

script:
  - php bin/phpunit

  #- composer csfix
  #- composer cscheck
  #- composer phpstan

  - php bin/console lint:yaml config
  - php bin/console lint:twig templates
  - php bin/console lint:xliff translations
  #- php bin/console security:check
  - php bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
